electionv1_0/electionv1_0/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('user/', include('user.urls')),

    path('', views.index, name='index'),
    path('special/', views.special, name='special'),
    path('user/', include('user.urls')),
    path('logout/', views.user_logout, name='logout'),
]

electionv1_0/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
]

electionv1_0/user/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, citizenship_number, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        # if not email:
        #     raise ValueError('Users must have an email address')

        user = self.model(
            citizenship_number=citizenship_number,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, citizenship_number, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            citizenship_number=citizenship_number,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )


    DISTRICT_CHOICES = (
        
        ('dolakha', 'Dolakha'),
        ('bhaktapur', 'Bhaktapur'),
        ('kathmandu', 'Kathmandu'),
        ('lalitpur', 'Lalitpur')
    )

    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
        ('others', 'Others')
    )

    ZONE_CHOICES = (
        ('janakpur', 'Janakpur'),
        ('bagmati', 'Bagmati')
    )

    # Demographic Details
    first_name = models.CharField(max_length=50,)
    middle_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50)
    mothers_name = models.CharField(verbose_name="Mother's Name", max_length=50)
    fathers_name = models.CharField(verbose_name="Father's Name", max_length=50)
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES)
    date_of_birth = models.DateField(null=True)
    education = models.CharField(max_length=50, blank=True, null=True)
    occupation = models.CharField(max_length=50,blank=True, null=True)
    post = models.CharField(max_length=50, blank=True, null=True)
    citizenship_number = models.CharField(verbose_name='Citizenship Number', max_length=20, null=True, unique=True)
    citizenship_issued_district = models.CharField(max_length=50, choices=DISTRICT_CHOICES)
    passport_number = models.IntegerField(verbose_name='Passport Number', null=True, blank=True)
    blood_group = models.CharField(max_length=6, blank=True, null=True)

    # Address Details
    # Present Address
    present_state = models.CharField(verbose_name='State', max_length=50)
    present_zone = models.CharField(verbose_name='Zone', max_length=50, choices=ZONE_CHOICES)
    present_district = models.CharField(verbose_name='District',max_length=255, choices=DISTRICT_CHOICES)
    present_rmm = models.CharField(verbose_name='Rural Muncipality/ Muncipality',max_length=255)
    present_ward = models.IntegerField(verbose_name='Ward No.', null=True)
    present_tole = models.CharField(verbose_name='Tole',max_length=255)
    present_block = models.IntegerField(verbose_name='Block No.', null=True, blank=True)
    present_contact = models.CharField(verbose_name='Contact No.',max_length=15)

    # Permanent Address
    permanent_state = models.CharField(verbose_name='State', max_length=50)
    permanent_zone = models.CharField(verbose_name='Zone', max_length=50, choices=ZONE_CHOICES)
    permanent_district = models.CharField(verbose_name='District', max_length=255, choices=DISTRICT_CHOICES)
    permanent_rmm = models.CharField(verbose_name='Rural Muncipality/ Muncipality', max_length=255)
    permanent_ward = models.IntegerField(verbose_name='Ward No.', blank=True, null=True)
    permanent_tole = models.CharField(verbose_name='Tole', max_length=255)
    permanent_block = models.IntegerField(verbose_name='Block No.', null=True, blank=True)
    permanent_contact = models.CharField(verbose_name='Contact No.',max_length=15)

    # Voting Details
    voting_state = models.CharField(verbose_name='State', max_length=50)
    voting_district = models.CharField(verbose_name='District', max_length=255, choices=DISTRICT_CHOICES)
    voting_rmm = models.CharField(verbose_name='Rural Muncipality/ Muncipality', max_length=255)
    voting_ward = models.IntegerField(verbose_name='Ward No.', blank=True, null=True)
    voting_tole = models.CharField(verbose_name='Tole', max_length=255)
    voting_booth = models.IntegerField(verbose_name='Booth No.', blank=True, null=True)
    voting_country = models.CharField(verbose_name='Country', max_length=255)
    email = models.EmailField(verbose_name='Email Address', max_length=255)

    is_voter = models.BooleanField(default=True)
    is_candidate = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'citizenship_number'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    # @property
    # def is_active(self):
    #     "Is the user active?"
    #     # # Simplest possible answer: Yes, always
    #     return self.is_active

electionv1_0/user/forms.py
from django import forms
from .models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('first_name',
                  'middle_name',
                  'last_name',
                  'mothers_name',
                  'fathers_name',
                  'gender',
                  'date_of_birth',
                  'education',
                  'occupation',
                  'post',
                  'citizenship_number',
                  'citizenship_issued_district',
                  'passport_number',
                  'blood_group',
                  'present_state',
                  'present_zone',
                  'present_district',
                  'present_rmm',
                  'present_ward',
                  'present_tole',
                  'present_block',
                  'present_contact',
                  'permanent_state',
                  'permanent_zone',
                  'permanent_district',
                  'permanent_rmm',
                  'permanent_ward',
                  'permanent_tole',
                  'permanent_block',
                  'permanent_contact',
                  'voting_state',
                  'voting_district',
                  'voting_rmm',
                  'voting_ward',
                  'voting_tole',
                  'voting_booth',
                  'voting_country',
                  'email',

                  'password',
                  'confirm_password',
                  )

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

electionv1_0/user/views.py
from django.contrib import admin
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import UserForm

def index(request):
    return render(request, 'user/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
            return render(request, 'user/login.html', {})
        else:
            return HttpResponse('Fill correctly!!')
    else:
        user_form = UserForm()
        context={'user_form': user_form, 
                'registered': registered
                }
        return render(request, 'user/registration.html', context)

def user_login(request):
    if request.method == 'POST':
        citizenship_number = request.POST.get('citizenship_number')
        password = request.POST.get('password')
        user = authenticate(citizenship_number=citizenship_number, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive")
        else:
            print('Someone tried to login and failed.')
            print("They used email: {} and password: {}".format(email, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'user/login.html', {})

electionv1_0/user/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Style.css -->
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,900|Ubuntu:400,700&display=swap"
        rel="stylesheet">
    <!-- Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</head>

<body>
    <!-- Navbar -->
    <nav class="nav-edit navbar navbar-expand-md navbar-light">
        <a id="brand" class="navbar-brand" href="{% url 'index' %}">election</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="#main">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <!-- <a class="nav-link" href="#reglog"><button type="button" class="btn btn-secondary">Registration</button></a> -->
                    <a class="nav-link" href="{% url 'user:register'%}"><button type="button" class="btn btn-secondary">Registration</button></a>
                </li>
                <li class="nav-item">
                    <!-- <a class="nav-link" href="#reglog"><button type="button" class="btn btn-outline-primary">Login</button></a> -->
                    <a class="nav-link" href="{% url 'user:user_login' %}"><button type="button" class="btn btn-outline-primary">Login</button></a>

                </li>
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownId">
                        <a class="dropdown-item" href="#">Action 1</a>
                        <a class="dropdown-item" href="#">Action 2</a>
                    </div>
                </li> -->
            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
        </div>


    </nav>
	
	{% block body_block %}
	
	{% endblock %}


    <!-- footer -->
    <div class="footer container-edit">
        <p class="footer-description">© Copyright 2020 NesCube</p>
    </div>

</body>

</html>

electionv1_0/user/templates/user/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Style.css -->
    <link rel="stylesheet" href="css/style.css">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,900|Ubuntu:400,700&display=swap"
        rel="stylesheet">
    <!-- Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</head>

<body>
    <!-- Navbar -->
    <nav class="nav-edit navbar navbar-expand-md navbar-light">
        <a id="brand" class="navbar-brand" href="#">election</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="#main">Dashboard<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Profile</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="#reglog"><button type="button"
                            class="btn btn-outline-primary">Logout</button></a>
                </li>
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownId">
                        <a class="dropdown-item" href="#">Action 1</a>
                        <a class="dropdown-item" href="#">Action 2</a>
                    </div>
                </li> -->
            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
        </div>


    </nav>

    <!-- home-header -->
    <div id="home-header" class="container-edit main-header">
        <div class="row">
            <div class="voters-details col-md-3">
                <img src="img/sudip.png" alt="">
            </div>
            <div class="col-md-6">
                <div class="voters-details">
                    <h4><strong>Sudip Bhujel</strong></h4>
                    <p>Kapan, Kathmandu</p>
                    <p>123456789</p>
                    <p>+9779844309479</p>
                    <a href="#">Edit details</a>
                </div>
            </div>
            <div class="voters-details col-md-3">
                <h5>Casted Vote?</h5>
                <button class="vote-status-btn btn">No</button>
            </div>
        </div>
        <!-- <div class="row">
            <div class="col-lg-8">
                <p class="index-heading">
                    Vote your candidates
                </p>
                <p class="index-description">
                    Both rest of know draw fond post as. It agreement defective to excellent. Feebly do engage of
                    narrow. Both rest of know draw fond post as. It agreement defective to excellent. Feebly do engage
                    of narrow. Both rest of know draw fond post as. It agreement defective
                </p>
            </div>
            <div class="col-lg-4">
                <img class="index-image" src="img/voting.png" alt="voting">
            </div>
        </div> -->
    </div>

    <!-- Candidates -->
    <div class="candidate-list">
        <h3 class="candidate-header">Candidates</h3>
        <div class="row">
            <div class="candidate-card col-lg-3 col-md-4 col-sm-6">
                <div class="card-theme card">
                    <div class="card-body">
                        <h5 class="candidate-name">Sudip Bhujel</h5>
                        
                        <img src="img/sudip.png" alt="" style="padding-bottom: 20px;">
                        <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
                        <p>Nepal Party</p>
                        <p><a href="#">More>></a></p>
                        
                        <form>
                            <button href="#" type="submit" class="login-button btn">Vote</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="candidate-card col-lg-3 col-md-4 col-sm-6">
                <div class="card-theme card">
                    <div class="card-body">
                        <h5 class="candidate-name">Sudip Bhujel</h5>
                        
                        <img src="img/sudip.png" alt="" style="padding-bottom: 20px;">
                        <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
                        <p>Nepal Party</p>
                        <p><a href="#">More>></a></p>
                        
                        <form>
                            <button href="#" type="submit" class="login-button btn">Vote</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="candidate-card col-lg-3 col-md-4 col-sm-6">
                <div class="card-theme card">
                    <div class="card-body">
                        <h5 class="candidate-name">Sudip Bhujel</h5>
                        
                        <img src="img/sudip.png" alt="" style="padding-bottom: 20px;">
                        <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
                        <p>Nepal Party</p>
                        <p><a href="#">More>></a></p>
                        
                        <form>
                            <button href="#" type="submit" class="login-button btn">Vote</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="candidate-card col-lg-3 col-md-4 col-sm-6">
                <div class="card-theme card">
                    <div class="card-body">
                        <h5 class="candidate-name">Sudip Bhujel</h5>
                        
                        <img src="img/sudip.png" alt="" style="padding-bottom: 20px;">
                        <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
                        <p>Nepal Party</p>
                        <p><a href="#">More>></a></p>
                        
                        <form>
                            <button href="#" type="submit" class="login-button btn">Vote</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="candidate-card col-lg-3 col-md-4 col-sm-6">
                <div class="card-theme card">
                    <div class="card-body">
                        <h5 class="candidate-name">Sudip Bhujel</h5>
                        
                        <img src="img/sudip.png" alt="" style="padding-bottom: 20px;">
                        <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
                        <p>Nepal Party</p>
                        <p><a href="#">More>></a></p>
                        
                        <form>
                            <button href="#" type="submit" class="login-button btn">Vote</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>

</body>

</html>

electionv1_0/user/templates/user/index.html
{% extends 'user/base.html' %}

{% load static %}

{% block body_block %}
    <!-- index-header -->
    <div id="main" class="container-edit main-header">
        <div class="row">
            <div class="col-lg-8">
                <p class="index-heading">
                    Vote your candidates
                </p>
                <p class="index-description">
                    Democracy is about voting and it’s about a majority vote. And it’s time that we started exercising the Democratic process. <br>
                    - Debbie Stabenow <br>
                    Let's vote!
                </p>
            </div>
            <div class="col-lg-4">
                <img class="index-image" src="{% static 'user/img/voting.png' %}" alt="voting">
            </div>
        </div>
    </div>

    <!-- reglog div -->
    <div id="reglog" class="reglog-container container-edit">
        <p class="reglog-heading">Secure your spot</p>
        <p class="reglog-description">Your each one vote counts, Let's take a step signing up and logging! </p>
        <a class="reslog-link" href="{% url 'user:register'%}"><button type="button" class="btn btn-secondary">Register</button></a>
        <a class="" href="{% url 'user:user_login'%}"><button type="button" class="btn btn-outline-primary">Login</button></a>
    </div>
{% endblock %}



electionv1_0/user/templates/user/login.html
{% extends 'user/base.html'%}
{% block body_block %}
    <!-- Login form -->

    <!-- <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="..." alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div> -->
    <div class="row">
        <div class="col-md-2 col-lg-3"></div>
        <div class="col-custom col-md-8 col-lg-6">
            <div class="card-theme card">
                <div class="card-body">
                    <h5 class="card-title">Login</h5>

                    <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->


                    <form method="POST" action="{% url 'user:user_login' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="citizenship_number">Citizenship Number</label>
                            <input type="text" class="form-control" name="citizenship_number" aria-describedby="citizenshipNumberHelp"
                                placeholder="Citizenship Number">
                            <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" name="password" placeholder="Password">
                        </div>
                        <!-- <div class="form-check">
                          <input type="checkbox" class="form-check-input" id="checkbox">
                          <label class="form-check-label" for="checkbox">Check me out</label>
                        </div> -->
                        <!-- <button href="#" type="Login" class="login-button btn">Login</button> -->
                        <input class="login-button btn" type="submit" name="" value="Login">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-2 col-lg-3"></div>
    </div>

{% endblock %}